### ISSUE TITLE
Problem with data set 40601

### ISSUE THREAD

**Issue by HeidiSeibold** [openml/website#135]
This is what I see:

![image](https://cloud.githubusercontent.com/assets/14146757/26033670/6687cc00-38b0-11e7-99df-5cd8f5a08aae.png)
 
It seems to be a quite new data set.

**Comment by joaquinvanschoren** [comment]
Good catch.

@janvanrijn this seems to be a Fantail issue. I get this exception:

[14-06-2017 14:34:29] [OK] [Process Dataset] Processing dataset 40601 on special request.
[14-06-2017 14:34:30] [OK] [Extract Features] Start downloading dataset: 40601
org.openml.apiconnector.io.ApiException: Dataset processed with error
	at org.openml.apiconnector.io.HttpConnector.readHttpResponse(HttpConnector.java:110)
	at org.openml.apiconnector.io.HttpConnector.doApiRequest(HttpConnector.java:58)
	at org.openml.apiconnector.io.OpenmlConnector.dataQualities(OpenmlConnector.java:316)
	at org.openml.webapplication.features.DatabaseUtils.GetQualitiesAvailable(DatabaseUtils.java:22)
	at org.openml.webapplication.features.FantailConnector.computeMetafeatures(FantailConnector.java:76)
	at org.openml.webapplication.features.FantailConnector.<init>(FantailConnector.java:58)
	at org.openml.webapplication.Main.main(Main.java:103)
{"error":"Dataset processed with error"}

**Comment by joaquinvanschoren** [comment]
Fixed. Plus I improved the way these errors are shown.
https://github.com/openml/website/pull/174
