### ISSUE TITLE
Evaluator keeps evaluating the same corrupt run

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/website#154]
Example: run 2766675
An error message should be added to Run_evaluated to skip over the run

```
[02-07-2017 21:42:27] [ERROR] [Process Run] An error occured during API call: Problem validating uploaded description file: XML does not correspond to XSD schema.
org.openml.apiconnector.io.ApiException: Problem validating uploaded description file: XML does not correspond to XSD schema.
        at org.openml.apiconnector.io.HttpConnector.readHttpResponse(HttpConnector.java:110)
        at org.openml.apiconnector.io.HttpConnector.doApiRequest(HttpConnector.java:47)
        at org.openml.apiconnector.io.OpenmlConnector.runEvaluate(OpenmlConnector.java:864)
        at org.openml.webapplication.EvaluateRun.evaluate(EvaluateRun.java:219)
        at org.openml.webapplication.EvaluateRun.<init>(EvaluateRun.java:66)
        at org.openml.webapplication.Main.main(Main.java:94)
[02-07-2017 21:42:27] [INFO] [Evaluate Run] Downloading task 2766675
```

**Comment by joaquinvanschoren** [comment]
These faulty runs seem to come from Weka, from a specific user: 
https://www.openml.org/u/1856/runs
